[api]
base_url = 'https://en.wikipedia.org/'

[theme]
text = 'white'
title = 'blue'
highlight = 'blue'
background = 'default'
search_match = 'blue'
highlight_text = 'white'
highlight_inactive = 'black'
border = 'round'

[logging]
enabled = true
log_dir = 'wiki_tui.log'
log_level = 'INFO'

[features]
links = true
toc = true

[keybindings.down]
key = 'j'
mode = 'normal'

[keybindings.up]
key = 'k'
mode = 'normal'

[keybindings.left]
key = 'h'
mode = 'normal'

[keybindings.right]
key = 'l'
mode = 'normal'

[keybindings.focus_next]
key = 'tab'
mode = 'normal'

[keybindings.focus_prev]
key = 'tab'
mode = 'shift'

[settings.toc]
position = 'right'
title = 'default'
min_width = 20
max_width = 60
scroll_x = true
scroll_y = true
item_format = '{NUMBER} {TEXT}'
